### PR TITLE
Upgrade to Node.js 16.14, migrate to esbuild, add Husky & Prettier

### PR DESCRIPTION
**Pull request by mikkopiu**
### Summary

Update from Node.js 8 to 16 and all production dependencies with it. Update and replace dev tools with more modern (and faster) alternatives such as [`esbuild`](https://esbuild.github.io/), and add [Prettier](https://prettier.io/) and [Husky](https://typicode.github.io/husky/#/).

### Detailed changes

- Update all Node.js versions from 8 to 16.14.0
- Update all production dependencies to their latest versions and perform any necessary migrations:
    - For Redis, just migrating to its native `Promise` interface is enough
    - Replace `throttle-function` with Lodash's `_.throttle` (abandoned and unnecessary package)
- Replace the slow and unnecessarily complex Babel with `esbuild` (builds in ~10ms now 🚀 )
- Add Husky for easy git hook management
- Add Prettier for unromantic and automatic code formatting (and reformat all code)
- Use the tried and tested nodemon as a development server instead of babel-watch (esbuild's own watch mode is designed more for browser apps)
- Replace `yarn` with modern npm:
    - `package-lock.json` and npm@8's dedupe mechanism rival yarn's features, and this simplifies our environment
- Add support for `SIGTERM` and `SIGQUIT` signals in the server
- Add `.dockerignore` to speed up image builds and remove unnecessary files from intermediate images
- Use CircleCI's official convenience images in CI

### CODE REVIEW

**Review by jpallari — APPROVED** [review]
This is awesome! Thank you @mikkopiu! Esbuild is very awesome and simplifies the setup considerably. I forgot that I used in a project of my own earlier.

**Comment by jpallari** [comment]
Credentials for Docker publishing failing. I'll sort out a machine user for that tomorrow.

**Comment by jpallari** [comment]
Updated the credentials for Docker Hub. Now it just fails because it tries to push tag `feat/node-16-upgrade`, which contains invalid characters. I guess `/` is not allowed in the tag. I think we can skip that for now and merge this as is.

**Comment by mikkopiu** [comment]
> Updated the credentials for Docker Hub. Now it just fails because it tries to push tag `feat/node-16-upgrade`, which contains invalid characters. I guess `/` is not allowed in the tag. I think we can skip that for now and merge this as is.

Added simple slash-to-dash replacement when used with tagging. CircleCI doesn't seem to provide a pre-cleaned branch name variable, like GitLab's `CI_COMMIT_REF_SLUG`.

**Pull request merged**
